image: node:latest

stages:
  - test
  - deploy

test-job:
  stage: test
  script:
    - npm install -g html-validator-cli
    - html-validator --file=index.html --verbose
  only:
    - main
  variables:
    SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"
  before_script:
    - apt-get update -y && apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa

deploy_to_server:
  stage: deploy
  script:
    - scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no index.html ec2-user@54.211.74.20:/var/www/html/
  only:
    - main