"""
NSE screener universe — Nifty 50 + Nifty Next 50 + Nifty 500 + Nifty Smallcap 250
~500 unique stocks hardcoded. No network call. Instant startup.
"""

_NIFTY50 = [
    "ADANIENT","ADANIPORTS","APOLLOHOSP","ASIANPAINT","AXISBANK",
    "BAJAJ-AUTO","BAJAJFINSV","BAJFINANCE","BHARTIARTL","BPCL",
    "BRITANNIA","CIPLA","COALINDIA","DIVISLAB","DLF",
    "DRREDDY","EICHERMOT","GRASIM","HCLTECH","HDFCBANK",
    "HDFCLIFE","HEROMOTOCO","HINDALCO","HINDUNILVR","ICICIBANK",
    "ICICIGI","INDUSINDBK","INFOSYS","ITC","JSWSTEEL",
    "KOTAKBANK","LT","M&M","MARUTI","NESTLEIND",
    "NTPC","ONGC","POWERGRID","RELIANCE","SBILIFE",
    "SBIN","SHRIRAMFIN","SUNPHARMA","TATAMOTORS","TATASTEEL",
    "TCS","TECHM","TITAN","TVSMOTOR","ULTRACEMCO","WIPRO",
]

_NIFTY_NEXT50 = [
    "ABB","AMBUJACEM","AUBANK","BAJAJHFL","BANKBARODA",
    "BEL","BERGEPAINT","BOSCHLTD","BSE","CANBK",
    "CGPOWER","CHOLAFIN","COFORGE","COLPAL","CUMMINSIND",
    "DABUR","DMART","FEDERALBNK","FORTIS","GODREJCP",
    "GODREJPROP","HAL","HAVELLS","ICICIAMC","INDUSTOWER",
    "IRCTC","JINDALSTEL","JUBLFOOD","LICI","LODHA",
    "LTTS","LUPIN","M&MFIN","MARICO","MAXHEALTH",
    "MPHASIS","NAUKRI","OBEROIRLTY","OFSS","PFC",
    "PERSISTENT","PIDILITIND","RECLTD","SCHAEFFLER","SIEMENS",
    "TATACHEM","TATACONSUM","TIINDIA","TORNTPHARM","TRENT",
    "VEDL","ZOMATO",
]

_NIFTY500_MID = [
    # Banks & Finance
    "BANDHANBNK","CANFINHOME","CHOLAHLDNG","CREDITACC","CSBBANK",
    "CUB","DCBBANK","EDELWEISS","EQUITASBNK","ESAFSFB",
    "FIVESTAR","HOMEFIRST","IDFCFIRSTB","IIFL","J&KBANK",
    "JMFINANCIL","KARURVYSYA","KFINTECH","LICHSGFIN","MANAPPURAM",
    "MOTILALOFS","MUTHOOTCAP","MUTHOOTFIN","PIRAMALFIN","POONAWALLA",
    "RBLBANK","REPCOHOME","SPANDANA","SURYODAY","TMB",
    "UCOBANK","UJJIVANSFB","UNIONBANK","UTIAMC","UTKARSHBNK","INDIANB",
    # IT & Tech
    "ANGELONE","CIGNITITEC","CYIENT","CYIENTDLM","ECLERX",
    "EMUDHRA","HAPPSTMNDS","INTELLECT","LATENTVIEW","MASTEK",
    "MCX","MSTCLTD","NAZARA","NETWEB","NEWGEN",
    "NUCLEUS","NUVAMA","NYKAA","PAYTM","QUESS",
    "RATEGAIN","ROUTE","TANLA","TATAELXSI","TEAMLEASE",
    "TEJASNET","ZAGGLE","ZENSARTECH","AURIONPRO","DATAPATTNS",
    # Pharma & Healthcare
    "AJANTPHARM","ALKEM","ASTRAZEN","AUROPHARMA","BIOCON",
    "CONCORDBIO","ERIS","FDC","GLAND","GLAXO",
    "GLENMARK","GRANULES","HERANBA","HIKAL","JBCHEPHARM",
    "LAURUSLABS","LAXMIDENTL","MANKIND","MARKSANS","NATCOPHARM",
    "NEULANDLAB","ORCHPHARMA","PFIZER","PGHL","SUVEN",
    "THYROCARE","UNICHEMLAB","WOCKPHARMA","ZYDUSLIFE","ZYDUSWELL","EMCURE","MEDANTA",
    # Auto & Ancillaries
    "BALKRISIND","BHARATFORG","CIEINDIA","ENDURANCE","ESCORTS",
    "EXIDEIND","FMGOETZE","FORCEMOT","GABRIEL","JAMNAAUTO",
    "JTEKTINDIA","KIRLOSBROS","KIRLOSENG","LUMAXTECH","MINDACORP",
    "MOTHERSON","MRF","NRBBEARING","PRICOLLTD","ROLEXRINGS",
    "SANSERA","SONACOMS","SUBROS","SUPRAJIT","TALBROAUTO",
    "TVSHLTD","TVSSRICHAK","UNOMINDA","TIIL","TIMKEN",
    # Capital Goods & Infra & Defence
    "ADANIGREEN","ADANIPOWER","ATGL","BHEL","BRIGADE",
    "CEIGALL","CRAFTSMAN","DREDGECORP","ENGINERSIN","GRSE",
    "HGINFRA","HUDCO","INOXGREEN","IRCON","IREDA",
    "IRFC","KEC","KNRCON","MIDHANI","MONTECARLO",
    "NBCC","NCC","NHPC","NLCINDIA","NTPCGREEN",
    "OLECTRA","POWERMECH","PSPPROJECT","PTC","RAILTEL",
    "RITES","RVNL","SJVN","STLTECH","SWSOLAR",
    "TITAGARH","TRANSRAILL","WAAREEENER","WABAG","WEBELSOLAR",
    "COCHINSHIP","MAZDOCK","PNCINFRA","TRIDENT",
    # FMCG & Consumer
    "BIKAJI","BATAINDIA","CAMPUS","DEVYANI","DODLA",
    "DOMS","GILLETTE","GOPAL","HERITGFOOD","HONASA",
    "JYOTHYLAB","KKCL","KRBL","LUXIND","MANYAVAR",
    "MATRIMONY","MEDPLUS","METROBRAND","PAGEIND","PARAGMILK",
    "PATANJALI","PVRINOX","RADICO","RAINBOW","RELAXO",
    "SAFARI","SHOPERSTOP","SPENCERS","SUNTV","UBL",
    "VSTIND","VSTTILLERS","VBL","WESTLIFE","WONDERLA","ZEEL","VENKEYS",
    # Chemicals & Energy
    "ALKYLAMINE","AARTIIND","AARTISURF","ADVENZYMES","AETHER",
    "BODALCHEM","CARBORUNIV","CHEMCON","CHEMPLASTS","COROMANDEL",
    "DEEPAKFERT","DEEPAKNTR","EIDPARRY","EPIGRAL","FINEORG",
    "FLUOROCHEM","GHCL","GNFC","GUJALKALI","GUJGASLTD",
    "IGL","IONEXCHANG","LXCHEM","NOCIL","PCBL",
    "RALLIS","ROSSARI","SUMICHEM","VINATIORGA","YASHO",
    "CHAMBLFERT","GSPL","GAIL","PETRONET","MGL",
    # Metals
    "APLAPOLLO","GPIL","HINDZINC","JINDALSAW","JSL",
    "JSWCEMENT","KIOCL","MOIL","MRPL","NATIONALUM",
    "NAVA","NMDC","RATNAMANI","SAIL","WELCORP","JSWENERGY",
    # Realty
    "AJMERA","ANANTRAJ","CHALET","DBREALTY","GODREJIND",
    "KOLTEPATIL","MAHLIFE","MAXESTATES","OMAXE","PHOENIXLTD",
    "PRESTIGE","SUNTECK","SOBHA","PURVA",
    # Textiles
    "ABFRL","ARVIND","RAYMOND","WELSPUNLIV","VARDHACRLC",
    # Diversified / Others
    "ASTRAL","CAMS","CARTRADE","CDSL","CERA",
    "DREAMFOLKS","EASEMYTRIP","ETHOSLTD","FLAIR","GICL",
    "GICRE","GRAVITA","GREENPANEL","GREENLAM","GRINDWELL",
    "IEX","INDHOTEL","INOXINDIA","ITCHOTELS","JSWINFRA",
    "JUBLINGREA","JUBLPHARMA","JUSTDIAL","KAJARIACER","KALPATARU",
    "KALYANKJIL","KAYNES","KEI","KIMS","MFSL",
    "NESCO","NUVOCO","OIL","POLYCAB","POLYMED",
    "PRINCEPIPE","PRSMJOHNSN","PROTEAN","PRUDENT","SCI",
    "SENCO","SFL","SKFINDIA","SOLARINDS","SOMANYCERA",
    "SONAMLTD","SONATSOFTW","SRF","STCINDIA","SUPREME",
    "SUPREMEIND","SYRMA","TARSONS","TATACAP","TATACOMM",
    "TATAINVEST","TATATECH","TCI","TCIEXP","THERMAX",
    "THOMASCOOK","UNIPARTS","VGUARD","VOLTAS","VOLTAMP",
    "VMART","VRLLOG","WHIRLPOOL","WINDLAS","XPROINDIA",
    "CROMPTON","BLUESTARCO","AMBER","DIXON","ELGIEQUIP",
    "SEAMECLTD","SAREGAMA","SANDHAR","SANOFI","SPARC",
    "ROOSARI","ROUTE","SAFARI","SAGILITY",
]

_NIFTY_SMALLCAP250 = [
    "AADHARHFC","ACEINTEG","ACMESOLAR","AEGISLOG","AEGISVOPAK",
    "AFFLE","AGI","AJAXENGG","AJOONI","AKUMS",
    "ALICON","ALLCARGO","ALPHAGEO","AMBIKCO","ANANDRATHI",
    "ANUP","APCOTEXIND","APOLLOPIPE","ARCHIDPLY","ARMANFIN",
    "ARTEMISMED","ASAHIINDIA","ASHIANA","ASHOKA","ASTEC",
    "ASTERDM","AVANTIFEED","BAJAJELEC","BANSALWIRE","BAYERCROP",
    "BEPL","BHAGERIA","BLISSGVS","BLUEDART","BLUEJET",
    "BSOFT","BUTTERFLY","CAPACITE","CAPLIPOINT","CARERATING",
    "CARYSIL","CASTROLIND","CEATLTD","CENTUM","CENTURYPLY",
    "CHOICEIN","CLEAN","CMSINFO","CONTROLPR","CRISIL",
    "CUPID","DCXINDIA","DEEPINDS","DICIND","ELECON",
    "ELIN","EMAMIPAP","EMKAY","EMMBI","ENIL",
    "ENTERO","ETHOSLTD","EXICOM","EXPLEOSOL","GABRIEL",
    "GAEL","GALAXYSURF","GANDHAR","GANESHBE","GARUDA",
    "GEECEE","GENUSPAPER","GENUSPOWER","GEOJITFSL","GESHIP",
    "GHCLTEXTIL","GILLANDERS","GINNIFILA","GIPCL","GKENERGY",
    "GLOBUSSPR","GOCLCORP","GOCOLORS","GODREJAGRO","GOKUL",
    "GOLDIAM","GOODLUCK","GPTINFRA","GREAVESCOT","GREENPLY",
    "GUFICBIO","GULFOILLUB","HARDWYN","HARIOMPIPE","HARSHA",
    "HCC","HCG","HEG","HESTERBIO","HFCL",
    "HUHTAMAKI","IMFA","INDIGOPNTS","IRIS","ISGEC",
    "IKIO","IRB","IXIGO","JASH","JBMA",
    "JKIPL","JKLAKSHMI","JKPAPER","JKTYRE","JPPOWER",
    "JYOTHYLAB","KALYANIFRG","KANSAINER","KRBL","LEMONTREE",
    "LTFOODS","MAPMYINDIA","MOIL","MOLDTKPAC","MOREPENLAB",
    "MTARTECH","NAVINFLUOR","NAVKARCORP","NELCO","NIITLTD",
    "NILKAMAL","NTPCGREEN","OLECTRA","ORIENTBELL","ORIENTELEC",
    "PANAMAPET","PATELENG","PENIND","PRINCEPIPE","PVRINOX",
    "RAIN","RALLIS","RAMCOCEM","RAMCOSYS","RATNAMANI",
    "REDTAPE","RITES","ROSSARI","SAFARI","SAREGAMA",
    "SEAMECLTD","SENCO","SJVN","SKIPPER","SOLARINDS",
    "SPARC","STLTECH","SUBROS","SUNDARMFIN","SUNDRMBRAK",
    "SUPRAJIT","SURYAROSNI","SUZLON","SYMPHONY","SYNGENE",
    "TEAMLEASE","TEGA","THYROCARE","TITAGARH","TORNTPOWER",
    "UNICHEMLAB","UNIPARTS","VENKEYS","VINATIORGA","VIPIND",
    "VOLTAMP","VRLLOG","WABAG","WELCORP","WONDERLA",
    "YASHO","YESBANK","ZEEL","ZENSARTECH",
]

# Deduplicated combined universe
_ALL = list(dict.fromkeys(
    _NIFTY50 + _NIFTY_NEXT50 + _NIFTY500_MID + _NIFTY_SMALLCAP250
))


def get_nse_tickers():
    """Return combined Nifty50+Next50+500+Smallcap250 in yfinance format."""
    return [f"{s}.NS" for s in _ALL]
